### ISSUE TITLE
 there no bounds limit for map?

### ISSUE THREAD

**Issue by romaster93** [deepak-1530/FastPlannerOctomap#1]
hi!!

I am setting avoidance and path through fast planner. But I think using octomap is lighter.

By using octomap is there no bounds limit for map? The fast planner has map size limitations.

thanks

**Comment by deepak-1530** [comment]
The occupancy map or octomap is global but the euclidean distance map (EDT map) is local. You can see that in Map.h file.

![image](https://user-images.githubusercontent.com/43798160/166632567-2986f5d5-b4f6-402c-9138-e468ad68eae1.png)

**Comment by romaster93** [comment]
I don't need to make a map. I simply need a good path planner. Can it function without map restrictions?

**Comment by deepak-1530** [comment]
You just need a way to check for collision or distance to nearest obstacles and remove the horizon range from the kinodynamic_astar.cpp.

**Comment by romaster93** [comment]
Thanks for the feedback! I'll do it.

**Comment by deepak-1530** [comment]
Close the issue if your problem is solved.
