### ISSUE TITLE
how can i connect my realsense depth camera with fastplanneroctomap

### ISSUE THREAD

**Issue by romaster93** [deepak-1530/FastPlannerOctomap#4]
hello

thank you for your nice repository.

I have built a simulation with ardupilot and it works very well with your repositories.

Now I'm trying to get it to work with my realsense d435 or d455. But it doesn't work.

I checked that the data of depth/image_raw is received well, but still no voxel grid or point cloud is created.

Could you possibly show the rs_camera.launch file you used?

thanks!

**Comment by deepak-1530** [comment]
It needs the pointcloud topic. Make sure you have enabled the pointcloud publishing in your launch file.
